name: Release Notification

on:
  workflow_dispatch:
    inputs:
      webhook:
        type: string
        required: true

jobs:
  test:
    name: Release Notification
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest

    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ github.event.inputs.webhook }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'A new nightly pre-release build has been generated! It is available for download here:\nhttps://github.com/Silverlan/pragma/releases/tag/nightly\n\nThis is NOT a stable release, use with caution! Only use this version for testing!'
