name: Run Tests

on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        options:
          - windows
          - ubuntu
        required: true

jobs:
  test:
    name: Tests - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ${{ github.event.inputs.os == 'windows' && 'windows-latest' || 'ubuntu-24.04' }}

    steps:
    - name: Set Initial Workflow Status
      run: echo "WORKFLOW_STATUS=success" >> $GITHUB_ENV

    - name: Run tests
      id: pragma
      uses: Silverlan/test_pragma_ci/github_actions/run_tests@main  # This points to the root directory of your repository where action.yml is located
      with:
        test-scripts: |
          "tests/assets/assets.lua"
          "tests/game/game.lua"
          "tests/pfm/launch_pfm.lua"
        working-directory: "pragma/build/install"
        artifacts-name: "assets"
        screenshot: true

    - name: Set Failure Workflow Status
      if: failure()
      run: echo "WORKFLOW_STATUS=failure" >> $GITHUB_ENV
      
    - name: Set Failure Workflow Status
      if: always()
      shell: bash
      run: |
        echo "WORKFLOW_STATUS=failure" >> $GITHUB_ENV
      
    - uses: LouisBrunner/checks-action@v2.0.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        conclusion: ${{ env.WORKFLOW_STATUS }}
        name: "Tests - ${{ matrix.config.os }}"
        output: |
          {"summary":"Test result is '${{ env.WORKFLOW_STATUS }}'."}
