name: Run Pragma Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-pragma:
    runs-on: ubuntu-latest

    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1259038706719789056/1ZROMvpB6zsi7JfwoQTMw79GB3EO5S-rf41JEJQKKY9481637AAgQbAbonx-iMe8_bPU
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project AAA has been deployed.'


      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Pragma
        id: download
        uses: Silverlan/test_pragma_ci/github_actions/download_pragma@main
        with:
          working-directory: "pragma/build/install"

      - name: Tests Import
        uses: actions/checkout@v4
        with:
          repository: Silverlan/pragma_tests_import
          token: ${{ secrets.PRAGMA_TESTS_IMPORT_TOKEN }}
          path: "pragma_tests_import"

      - name: Copy files to target directory
        shell: bash
        run: |
          cp -rf pragma_tests_import/* pragma/build/install/
          rm -rf pragma_tests_import

      - name: Copy
        shell: bash
        run: |
          cp -rf test_x.lua pragma/build/install/lua/tests/
          cp -rf test_y.lua pragma/build/install/lua/tests/

      - name: Run tests
        id: pragma
        uses: Silverlan/test_pragma_ci/github_actions/run_tests@main  # This points to the root directory of your repository where action.yml is located
        with:
          test-scripts: |
            "tests/import_assets.lua"
            "tests/test_y.lua"
          working-directory: "pragma/build/install"
          artifacts-name: "assets"
          screenshot: true
