name: Run Pragma Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-pragma:
    runs-on: windows-latest

    steps:
      - name: Run tests
        id: pragma
        uses: Silverlan/test_pragma_ci/github_actions/run_tests@main  # This points to the root directory of your repository where action.yml is located
        with:
          test-scripts: |
            "tests/assets/assets.lua"
            "tests/game/game.lua"
            "tests/pfm/launch_pfm.lua"
          artifacts-name: "assets"
          screenshot: true
