name: Run Pragma Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-pragma:
    runs-on: windows-latest

    steps:
      - name: Download Pragma
        id: download
        uses: Silverlan/test_pragma_ci/github_actions/download_pragma@main
        with:
          working-directory: "pragma/build/install"

      - name: Tests Import
        uses: actions/checkout@v4
        with:
          repository: Silverlan/pragma_tests_import
          token: ${{ secrets.PRAGMA_TESTS_IMPORT_TOKEN }}
          path: "pragma/build/install"

      - name: Run tests
        id: pragma
        uses: Silverlan/test_pragma_ci/github_actions/run_tests@main  # This points to the root directory of your repository where action.yml is located
        with:
          test-scripts: |
            "tests/import_assets.lua"
          working-directory: "pragma/build/install"
          artifacts-name: "assets"
          screenshot: true
